name: SNMPSIM CI

on:
  pull_request:
    branches: ["*"]

jobs:
  check_funktion:
    runs-on: ubuntu-latest
    env:
      CFLAGS: "-Wall -Wextra -Werror"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip

    - name: Install pip packages
      run: pip install -r .github/requirements.txt
 
    - name: Install dependencies
      run: |
        sudo .github/prepare_ubuntu.sh

    - name: Make
      run: make

    - name: Start simmulation
      run: |
        setup-snmpsim-data /tmp/data
        /opt/hostedtoolcache/Python/3.10.14/x64/bin/snmpsim-command-responder --daemonize --pid-file /tmp/snmp --data-dir=/tmp/data/network/switch/ --agent-udpv4-endpoint=127.0.0.1:1611

    - name: Sleep
      run: sleep 120s
      shell: bash

    - name: check_cisco_health
      run: |
        chmod 0755 check_cisco_health
        ./check_cisco_health -h 127.0.0.1:1611 -c cisco-c3560 -t 30000
